# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\upgrade.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(907, 613)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.upgradeDetail = QtWidgets.QTableWidget(self.centralwidget)
        self.upgradeDetail.setGeometry(QtCore.QRect(10, 40, 881, 501))
        self.upgradeDetail.setObjectName("upgradeDetail")
        self.upgradeDetail.setColumnCount(0)
        self.upgradeDetail.setRowCount(0)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(730, 580, 158, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout_Bottom = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_Bottom.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_Bottom.setObjectName("horizontalLayout_Bottom")
        self.Button_cancel = QtWidgets.QPushButton(self.widget)
        self.Button_cancel.setObjectName("Button_cancel")
        self.horizontalLayout_Bottom.addWidget(self.Button_cancel)
        self.Button_upgrade = QtWidgets.QPushButton(self.widget)
        self.Button_upgrade.setObjectName("Button_upgrade")
        self.horizontalLayout_Bottom.addWidget(self.Button_upgrade)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(11, 550, 297, 25))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_File = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_File.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_File.setObjectName("horizontalLayout_File")
        self.Button_input_file = QtWidgets.QPushButton(self.widget1)
        self.Button_input_file.setObjectName("Button_input_file")
        self.horizontalLayout_File.addWidget(self.Button_input_file)
        self.lineEdit_filePath = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_filePath.setObjectName("lineEdit_filePath")
        self.horizontalLayout_File.addWidget(self.lineEdit_filePath)
        self.Button_download_file = QtWidgets.QPushButton(self.widget1)
        self.Button_download_file.setObjectName("Button_download_file")
        self.horizontalLayout_File.addWidget(self.Button_download_file)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(10, 10, 371, 21))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_number = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_number.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_number.setObjectName("horizontalLayout_number")
        self.label_total_file = QtWidgets.QLabel(self.widget2)
        self.label_total_file.setObjectName("label_total_file")
        self.horizontalLayout_number.addWidget(self.label_total_file)
        self.textBrowser_total_file = QtWidgets.QTextBrowser(self.widget2)
        self.textBrowser_total_file.setOpenLinks(False)
        self.textBrowser_total_file.setObjectName("textBrowser_total_file")
        self.horizontalLayout_number.addWidget(self.textBrowser_total_file)
        self.label_upgrade_success = QtWidgets.QLabel(self.widget2)
        self.label_upgrade_success.setObjectName("label_upgrade_success")
        self.horizontalLayout_number.addWidget(self.label_upgrade_success)
        self.textBrowser_upgrade_success = QtWidgets.QTextBrowser(self.widget2)
        self.textBrowser_upgrade_success.setOpenLinks(False)
        self.textBrowser_upgrade_success.setObjectName("textBrowser_upgrade_success")
        self.horizontalLayout_number.addWidget(self.textBrowser_upgrade_success)
        self.label_upgrade_failed = QtWidgets.QLabel(self.widget2)
        self.label_upgrade_failed.setObjectName("label_upgrade_failed")
        self.horizontalLayout_number.addWidget(self.label_upgrade_failed)
        self.textBrowser_upgrade_failed = QtWidgets.QTextBrowser(self.widget2)
        self.textBrowser_upgrade_failed.setOpenLinks(False)
        self.textBrowser_upgrade_failed.setObjectName("textBrowser_upgrade_failed")
        self.horizontalLayout_number.addWidget(self.textBrowser_upgrade_failed)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Upgrade"))
        self.Button_cancel.setText(_translate("MainWindow", "取消"))
        self.Button_upgrade.setText(_translate("MainWindow", "升级"))
        self.Button_input_file.setText(_translate("MainWindow", "导入文件"))
        self.Button_download_file.setText(_translate("MainWindow", "下载模板"))
        self.label_total_file.setText(_translate("MainWindow", "升级总数:"))
        self.label_upgrade_success.setText(_translate("MainWindow", "成功升级:"))
        self.label_upgrade_failed.setText(_translate("MainWindow", "失败数量"))
