# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tool_text_rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetRSA(object):
    def setupUi(self, WidgetRSA):
        WidgetRSA.setObjectName("WidgetRSA")
        WidgetRSA.resize(1101, 724)
        self.horizontalLayout = QtWidgets.QHBoxLayout(WidgetRSA)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(WidgetRSA)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.listWidget)
        self.rsaStackedWidget = QtWidgets.QStackedWidget(WidgetRSA)
        self.rsaStackedWidget.setObjectName("rsaStackedWidget")
        self.horizontalLayout.addWidget(self.rsaStackedWidget)

        self.retranslateUi(WidgetRSA)
        QtCore.QMetaObject.connectSlotsByName(WidgetRSA)

    def retranslateUi(self, WidgetRSA):
        _translate = QtCore.QCoreApplication.translate
        WidgetRSA.setWindowTitle(_translate("WidgetRSA", "Form"))
