# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tool_text_json.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetJson(object):
    def setupUi(self, WidgetJson):
        WidgetJson.setObjectName("WidgetJson")
        WidgetJson.resize(1102, 663)
        self.verticalLayout = QtWidgets.QVBoxLayout(WidgetJson)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(WidgetJson)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.textBrowser = QtWidgets.QTextBrowser(WidgetJson)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(WidgetJson)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.cleanBtn = QtWidgets.QPushButton(WidgetJson)
        self.cleanBtn.setObjectName("cleanBtn")
        self.horizontalLayout_2.addWidget(self.cleanBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(WidgetJson)
        QtCore.QMetaObject.connectSlotsByName(WidgetJson)

    def retranslateUi(self, WidgetJson):
        _translate = QtCore.QCoreApplication.translate
        WidgetJson.setWindowTitle(_translate("WidgetJson", "Form"))
        self.pushButton.setText(_translate("WidgetJson", "Format"))
        self.cleanBtn.setText(_translate("WidgetJson", "Clean"))
