# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tool_text_rsa_encrypt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetRsaEncrypt(object):
    def setupUi(self, WidgetRsaEncrypt):
        WidgetRsaEncrypt.setObjectName("WidgetRsaEncrypt")
        WidgetRsaEncrypt.resize(872, 732)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(WidgetRsaEncrypt)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(WidgetRsaEncrypt)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(WidgetRsaEncrypt)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(WidgetRsaEncrypt)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.textEdit_3 = QtWidgets.QTextEdit(WidgetRsaEncrypt)
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout_3.addWidget(self.textEdit_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(WidgetRsaEncrypt)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.textBrowser = QtWidgets.QTextBrowser(WidgetRsaEncrypt)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_4.addWidget(self.textBrowser)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(WidgetRsaEncrypt)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(WidgetRsaEncrypt)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(WidgetRsaEncrypt)
        QtCore.QMetaObject.connectSlotsByName(WidgetRsaEncrypt)

    def retranslateUi(self, WidgetRsaEncrypt):
        _translate = QtCore.QCoreApplication.translate
        WidgetRsaEncrypt.setWindowTitle(_translate("WidgetRsaEncrypt", "Form"))
        self.label.setText(_translate("WidgetRsaEncrypt", "密钥"))
        self.label_3.setText(_translate("WidgetRsaEncrypt", "待加密文本"))
        self.label_4.setText(_translate("WidgetRsaEncrypt", "加密结果"))
        self.pushButton.setText(_translate("WidgetRsaEncrypt", "加密"))
        self.pushButton_2.setText(_translate("WidgetRsaEncrypt", "解密"))
