# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tool_image_base64.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetImageBase64(object):
    def setupUi(self, WidgetImageBase64):
        WidgetImageBase64.setObjectName("WidgetImageBase64")
        WidgetImageBase64.resize(1097, 582)
        self.verticalLayout = QtWidgets.QVBoxLayout(WidgetImageBase64)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.text_result = QtWidgets.QTextEdit(WidgetImageBase64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_result.sizePolicy().hasHeightForWidth())
        self.text_result.setSizePolicy(sizePolicy)
        self.text_result.setAutoFillBackground(True)
        self.text_result.setObjectName("text_result")
        self.horizontalLayout.addWidget(self.text_result)
        self.label_img = QtWidgets.QLabel(WidgetImageBase64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_img.sizePolicy().hasHeightForWidth())
        self.label_img.setSizePolicy(sizePolicy)
        self.label_img.setMinimumSize(QtCore.QSize(0, 192))
        self.label_img.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_img.setAutoFillBackground(True)
        self.label_img.setStyleSheet("")
        self.label_img.setFrameShape(QtWidgets.QFrame.Box)
        self.label_img.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img.setObjectName("label_img")
        self.horizontalLayout.addWidget(self.label_img)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.base64ToImgBtn = QtWidgets.QPushButton(WidgetImageBase64)
        self.base64ToImgBtn.setObjectName("base64ToImgBtn")
        self.horizontalLayout_2.addWidget(self.base64ToImgBtn)
        self.imgToBase64Btn = QtWidgets.QPushButton(WidgetImageBase64)
        self.imgToBase64Btn.setObjectName("imgToBase64Btn")
        self.horizontalLayout_2.addWidget(self.imgToBase64Btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.cleanBtn = QtWidgets.QPushButton(WidgetImageBase64)
        self.cleanBtn.setObjectName("cleanBtn")
        self.horizontalLayout_2.addWidget(self.cleanBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(WidgetImageBase64)
        QtCore.QMetaObject.connectSlotsByName(WidgetImageBase64)

    def retranslateUi(self, WidgetImageBase64):
        _translate = QtCore.QCoreApplication.translate
        WidgetImageBase64.setWindowTitle(_translate("WidgetImageBase64", "Form"))
        self.label_img.setText(_translate("WidgetImageBase64", "ResultZone"))
        self.base64ToImgBtn.setText(_translate("WidgetImageBase64", "Base64ToImg"))
        self.imgToBase64Btn.setText(_translate("WidgetImageBase64", "ImgToBase64"))
        self.cleanBtn.setText(_translate("WidgetImageBase64", "Clean"))
