# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tool_text_rsa_create_verify_secret_key.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetRsaCreateSecretKey(object):
    def setupUi(self, WidgetRsaCreateSecretKey):
        WidgetRsaCreateSecretKey.setObjectName("WidgetRsaCreateSecretKey")
        WidgetRsaCreateSecretKey.resize(938, 743)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(WidgetRsaCreateSecretKey)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(WidgetRsaCreateSecretKey)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(WidgetRsaCreateSecretKey)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(WidgetRsaCreateSecretKey)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.textEdit_3 = QtWidgets.QTextEdit(WidgetRsaCreateSecretKey)
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout_3.addWidget(self.textEdit_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_3 = QtWidgets.QPushButton(WidgetRsaCreateSecretKey)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_4 = QtWidgets.QPushButton(WidgetRsaCreateSecretKey)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(WidgetRsaCreateSecretKey)
        QtCore.QMetaObject.connectSlotsByName(WidgetRsaCreateSecretKey)

    def retranslateUi(self, WidgetRsaCreateSecretKey):
        _translate = QtCore.QCoreApplication.translate
        WidgetRsaCreateSecretKey.setWindowTitle(_translate("WidgetRsaCreateSecretKey", "Form"))
        self.label.setText(_translate("WidgetRsaCreateSecretKey", "公钥"))
        self.label_3.setText(_translate("WidgetRsaCreateSecretKey", "私钥"))
        self.pushButton_3.setText(_translate("WidgetRsaCreateSecretKey", "创建"))
        self.pushButton_4.setText(_translate("WidgetRsaCreateSecretKey", "验证"))
