# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool_net_local_ip.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetLocalDevice(object):
    def setupUi(self, WidgetLocalDevice):
        WidgetLocalDevice.setObjectName("WidgetLocalDevice")
        WidgetLocalDevice.resize(1102, 682)
        self.verticalLayout = QtWidgets.QVBoxLayout(WidgetLocalDevice)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(WidgetLocalDevice)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(WidgetLocalDevice)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listWidget = QtWidgets.QListWidget(WidgetLocalDevice)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.searchBtn = QtWidgets.QPushButton(WidgetLocalDevice)
        self.searchBtn.setObjectName("searchBtn")
        self.horizontalLayout_2.addWidget(self.searchBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(WidgetLocalDevice)
        QtCore.QMetaObject.connectSlotsByName(WidgetLocalDevice)

    def retranslateUi(self, WidgetLocalDevice):
        _translate = QtCore.QCoreApplication.translate
        WidgetLocalDevice.setWindowTitle(_translate("WidgetLocalDevice", "Form"))
        self.label.setText(_translate("WidgetLocalDevice", "本机IP地址"))
        self.searchBtn.setText(_translate("WidgetLocalDevice", "开始搜索"))
