# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tools.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1096, 676)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text_result = QtWidgets.QTextEdit(self.centralwidget)
        self.text_result.setGeometry(QtCore.QRect(10, 10, 471, 621))
        self.text_result.setAutoFillBackground(True)
        self.text_result.setObjectName("text_result")
        self.cleanBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cleanBtn.setGeometry(QtCore.QRect(500, 590, 75, 23))
        self.cleanBtn.setObjectName("cleanBtn")
        self.label_img = QtWidgets.QLabel(self.centralwidget)
        self.label_img.setGeometry(QtCore.QRect(600, 10, 481, 621))
        self.label_img.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_img.setAutoFillBackground(True)
        self.label_img.setStyleSheet("")
        self.label_img.setFrameShape(QtWidgets.QFrame.Box)
        self.label_img.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img.setObjectName("label_img")
        self.groupBoxImage = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxImage.setGeometry(QtCore.QRect(490, 90, 101, 101))
        self.groupBoxImage.setObjectName("groupBoxImage")
        self.imgToBase64Btn = QtWidgets.QPushButton(self.groupBoxImage)
        self.imgToBase64Btn.setGeometry(QtCore.QRect(10, 60, 81, 31))
        self.imgToBase64Btn.setObjectName("imgToBase64Btn")
        self.base64ToImgBtn = QtWidgets.QPushButton(self.groupBoxImage)
        self.base64ToImgBtn.setGeometry(QtCore.QRect(10, 20, 81, 31))
        self.base64ToImgBtn.setObjectName("base64ToImgBtn")
        self.groupBoxText = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxText.setGeometry(QtCore.QRect(489, 9, 101, 81))
        self.groupBoxText.setObjectName("groupBoxText")
        self.jsonFromatBtn = QtWidgets.QPushButton(self.groupBoxText)
        self.jsonFromatBtn.setGeometry(QtCore.QRect(10, 20, 81, 31))
        self.jsonFromatBtn.setObjectName("jsonFromatBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Utils"))
        self.cleanBtn.setText(_translate("MainWindow", "Clean"))
        self.label_img.setText(_translate("MainWindow", "ResultZone"))
        self.groupBoxImage.setTitle(_translate("MainWindow", "Image"))
        self.imgToBase64Btn.setText(_translate("MainWindow", "ImgToBase64"))
        self.base64ToImgBtn.setText(_translate("MainWindow", "Base64ToImg"))
        self.groupBoxText.setTitle(_translate("MainWindow", "Text"))
        self.jsonFromatBtn.setText(_translate("MainWindow", "JsonFormat"))
