# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool_text_json.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetJson(object):
    def setupUi(self, WidgetJson):
        WidgetJson.setObjectName("WidgetJson")
        WidgetJson.resize(1102, 663)
        self.verticalLayout = QtWidgets.QVBoxLayout(WidgetJson)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(WidgetJson)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.treeView = QtWidgets.QTreeView(WidgetJson)
        self.treeView.setObjectName("treeView")
        self.horizontalLayout.addWidget(self.treeView)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formatBtn = QtWidgets.QPushButton(WidgetJson)
        self.formatBtn.setObjectName("formatBtn")
        self.horizontalLayout_2.addWidget(self.formatBtn)
        self.reduceBtn = QtWidgets.QPushButton(WidgetJson)
        self.reduceBtn.setObjectName("reduceBtn")
        self.horizontalLayout_2.addWidget(self.reduceBtn)
        self.escapedBtn = QtWidgets.QPushButton(WidgetJson)
        self.escapedBtn.setObjectName("escapedBtn")
        self.horizontalLayout_2.addWidget(self.escapedBtn)
        self.unescapedBtn = QtWidgets.QPushButton(WidgetJson)
        self.unescapedBtn.setObjectName("unescapedBtn")
        self.horizontalLayout_2.addWidget(self.unescapedBtn)
        self.unicodeToChineseCheckBox = QtWidgets.QCheckBox(WidgetJson)
        self.unicodeToChineseCheckBox.setChecked(True)
        self.unicodeToChineseCheckBox.setObjectName("unicodeToChineseCheckBox")
        self.horizontalLayout_2.addWidget(self.unicodeToChineseCheckBox)
        self.base64valueCheckBox = QtWidgets.QCheckBox(WidgetJson)
        self.base64valueCheckBox.setObjectName("base64valueCheckBox")
        self.horizontalLayout_2.addWidget(self.base64valueCheckBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.cleanBtn = QtWidgets.QPushButton(WidgetJson)
        self.cleanBtn.setObjectName("cleanBtn")
        self.horizontalLayout_2.addWidget(self.cleanBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(WidgetJson)
        QtCore.QMetaObject.connectSlotsByName(WidgetJson)

    def retranslateUi(self, WidgetJson):
        _translate = QtCore.QCoreApplication.translate
        WidgetJson.setWindowTitle(_translate("WidgetJson", "Form"))
        self.formatBtn.setText(_translate("WidgetJson", "格式化"))
        self.reduceBtn.setText(_translate("WidgetJson", "压缩"))
        self.escapedBtn.setText(_translate("WidgetJson", "转义"))
        self.unescapedBtn.setText(_translate("WidgetJson", "去转义"))
        self.unicodeToChineseCheckBox.setText(_translate("WidgetJson", "unicode转中文"))
        self.base64valueCheckBox.setText(_translate("WidgetJson", "Base64解码"))
        self.cleanBtn.setText(_translate("WidgetJson", "清空"))
