# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tool_text_rsa_change_private_key_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetRsaChangePrivateKeyPassword(object):
    def setupUi(self, WidgetRsaChangePrivateKeyPassword):
        WidgetRsaChangePrivateKeyPassword.setObjectName("WidgetRsaChangePrivateKeyPassword")
        WidgetRsaChangePrivateKeyPassword.resize(919, 735)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(WidgetRsaChangePrivateKeyPassword)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(WidgetRsaChangePrivateKeyPassword)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(WidgetRsaChangePrivateKeyPassword)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(WidgetRsaChangePrivateKeyPassword)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(WidgetRsaChangePrivateKeyPassword)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.label_3 = QtWidgets.QLabel(WidgetRsaChangePrivateKeyPassword)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(WidgetRsaChangePrivateKeyPassword)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(WidgetRsaChangePrivateKeyPassword)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.textBrowser = QtWidgets.QTextBrowser(WidgetRsaChangePrivateKeyPassword)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_4.addWidget(self.textBrowser)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(WidgetRsaChangePrivateKeyPassword)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(WidgetRsaChangePrivateKeyPassword)
        QtCore.QMetaObject.connectSlotsByName(WidgetRsaChangePrivateKeyPassword)

    def retranslateUi(self, WidgetRsaChangePrivateKeyPassword):
        _translate = QtCore.QCoreApplication.translate
        WidgetRsaChangePrivateKeyPassword.setWindowTitle(_translate("WidgetRsaChangePrivateKeyPassword", "Form"))
        self.label.setText(_translate("WidgetRsaChangePrivateKeyPassword", "私钥"))
        self.label_2.setText(_translate("WidgetRsaChangePrivateKeyPassword", "原密码"))
        self.label_3.setText(_translate("WidgetRsaChangePrivateKeyPassword", "新密码"))
        self.label_4.setText(_translate("WidgetRsaChangePrivateKeyPassword", "修改后"))
        self.pushButton.setText(_translate("WidgetRsaChangePrivateKeyPassword", "开始"))
