# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tool_text_timestamp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetTimestamp(object):
    def setupUi(self, WidgetTimestamp):
        WidgetTimestamp.setObjectName("WidgetTimestamp")
        WidgetTimestamp.resize(1108, 670)
        self.verticalLayout = QtWidgets.QVBoxLayout(WidgetTimestamp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(WidgetTimestamp)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 4, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(WidgetTimestamp)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 3, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(WidgetTimestamp)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 3, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(WidgetTimestamp)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(WidgetTimestamp)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(WidgetTimestamp)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(WidgetTimestamp)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(WidgetTimestamp)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(WidgetTimestamp)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 4, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(WidgetTimestamp)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 589, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(WidgetTimestamp)
        QtCore.QMetaObject.connectSlotsByName(WidgetTimestamp)

    def retranslateUi(self, WidgetTimestamp):
        _translate = QtCore.QCoreApplication.translate
        WidgetTimestamp.setWindowTitle(_translate("WidgetTimestamp", "Form"))
        self.pushButton_2.setText(_translate("WidgetTimestamp", "PushButton"))
        self.label_2.setText(_translate("WidgetTimestamp", "时间"))
        self.label.setText(_translate("WidgetTimestamp", "时间戳"))
        self.pushButton.setText(_translate("WidgetTimestamp", "PushButton"))
