# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'waiting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QWaiting(object):
    def setupUi(self, QWaiting):
        QWaiting.setObjectName("QWaiting")
        QWaiting.resize(462, 300)
        self.label = QtWidgets.QLabel(QWaiting)
        self.label.setGeometry(QtCore.QRect(43, 31, 391, 91))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(QWaiting)
        self.label_2.setGeometry(QtCore.QRect(130, 180, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(29)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(QWaiting)
        QtCore.QMetaObject.connectSlotsByName(QWaiting)

    def retranslateUi(self, QWaiting):
        _translate = QtCore.QCoreApplication.translate
        QWaiting.setWindowTitle(_translate("QWaiting", "Form"))
        self.label.setText(_translate("QWaiting", "TextLabel"))
        self.label_2.setText(_translate("QWaiting", "正在进行中"))
